name: dev

on:
  push:
    paths:
      - .github/workflows/dev.yml
      - dev/**

jobs:
  build-docker-image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build/Tag/Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dev/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bayabiz/dev:latest,bayabiz/dev:${{ github.sha }}
