name: dev

on:
  push:
    paths:
      - .github/workflows/dev.yml
      - dev/**

jobs:
  build-docker-image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # https://github.com/docker/buildx/issues/495#issuecomment-918925854
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build/Tag/Push Docker Image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=bayabiz/dev:buildcache
          cache-to: type=registry,ref=bayabiz/dev:buildcache,mode=max
          context: .
          file: ./dev/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bayabiz/dev:latest,bayabiz/dev:${{ github.sha }}
